
services:
  frontend1:
    build: ./frontEndWebSite
    ports:
      - "3000:3000"
    container_name: frontEndWebSite

  frontend2:
    build: ./frontEndManagement
    ports:
      - "4200:4200"
    volumes:
      - ./frontEndManagement:/app
    container_name: frontEndManagement
  backend:
    build: ./back-end
    ports:
      - "3333:3333"
    container_name: backend

  dev-db:
    image: mongo:latest
    container_name: dev-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:mongo
      - MONGO_INITDB_ROOT_PASSWORD:123  
    networks:
      - compselect-network
networks:
  compselect-network:
